"""empty message

Revision ID: 09895464ee2b
Revises: 
Create Date: 2018-10-06 09:38:13.245275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09895464ee2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazina', sa.String(length=100), nullable=True),
    sa.Column('resi', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('umusaruro', sa.Integer(), nullable=True),
    sa.Column('umuceriYagurijwe', sa.Integer(), nullable=True),
    sa.Column('umuceriWoKurya', sa.Integer(), nullable=True),
    sa.Column('umuceriWoKugurisha', sa.Integer(), nullable=True),
    sa.Column('igiciroCyaKimwe', sa.Integer(), nullable=True),
    sa.Column('umusanzu', sa.Integer(), nullable=True),
    sa.Column('amafaraYose', sa.Integer(), nullable=True),
    sa.Column('amafarangaYoGutonoza', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coopMemberBankAccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberName', sa.String(length=100), nullable=True),
    sa.Column('bankName', sa.String(length=50), nullable=True),
    sa.Column('bankAccountNumber', sa.String(length=50), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['umusaruro_resi'], ['umusaruro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bankAccountNumber'),
    sa.UniqueConstraint('bankName')
    )
    op.create_table('ibyakoreshejwe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deamAndSup', sa.Integer(), nullable=True),
    sa.Column('ibihanoCoop', sa.Integer(), nullable=True),
    sa.Column('APKSAMAKIbihano', sa.Integer(), nullable=True),
    sa.Column('ibiraraneNPKandUREA', sa.Integer(), nullable=True),
    sa.Column('umusoroWakarere', sa.Integer(), nullable=True),
    sa.Column('kwishyuraItsinda', sa.Integer(), nullable=True),
    sa.Column('sheeting', sa.Integer(), nullable=True),
    sa.Column('PandS', sa.Integer(), nullable=True),
    sa.Column('ibyoYagurijwe', sa.Integer(), nullable=True),
    sa.Column('ibindiYasbwe', sa.Integer(), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['umusaruro_resi'], ['umusaruro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inyongeramusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BriqueteUnity', sa.Float(), nullable=True),
    sa.Column('BriquetePU', sa.Integer(), nullable=True),
    sa.Column('DapAndNPKUnity', sa.Float(), nullable=True),
    sa.Column('DapAndNPKpu', sa.Integer(), nullable=True),
    sa.Column('KCLUnity', sa.Float(), nullable=True),
    sa.Column('KCLpu', sa.Integer(), nullable=True),
    sa.Column('ImbutoIngano', sa.Float(), nullable=True),
    sa.Column('ImbutoPU', sa.Integer(), nullable=True),
    sa.Column('RedevanceUbuso', sa.Float(), nullable=True),
    sa.Column('RedevancePU', sa.Integer(), nullable=True),
    sa.Column('ImifukaAgaciro', sa.Integer(), nullable=True),
    sa.Column('ImifukaYishyuwe', sa.Integer(), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['umusaruro_resi'], ['umusaruro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inyongeramusaruro')
    op.drop_table('ibyakoreshejwe')
    op.drop_table('coopMemberBankAccounts')
    op.drop_table('umusaruro')
    # ### end Alembic commands ###
