"""empty message

Revision ID: 530d2186b41f
Revises: 
Create Date: 2018-10-18 12:05:55.453189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530d2186b41f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inyongeramusaruro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazina', sa.String(length=200), nullable=True),
    sa.Column('BriqueteUnity', sa.Float(), nullable=True),
    sa.Column('BriquetePU', sa.Integer(), nullable=True),
    sa.Column('DapAndNPKUnity', sa.Float(), nullable=True),
    sa.Column('DapAndNPKpu', sa.Integer(), nullable=True),
    sa.Column('KCLUnity', sa.Float(), nullable=True),
    sa.Column('KCLpu', sa.Integer(), nullable=True),
    sa.Column('ImbutoIngano', sa.Float(), nullable=True),
    sa.Column('ImbutoPU', sa.Integer(), nullable=True),
    sa.Column('RedevanceUbuso', sa.Float(), nullable=True),
    sa.Column('RedevancePU', sa.Integer(), nullable=True),
    sa.Column('ImifukaAgaciro', sa.Integer(), nullable=True),
    sa.Column('ImifukaYishyuwe', sa.Integer(), nullable=True),
    sa.Column('umusaruro_resi', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=200), nullable=True),
    sa.Column('umwakaWisarura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.email'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('umusaruro_resi')
    )
    op.drop_constraint('coopMemberBankAccounts_ibfk_3', 'coopMemberBankAccounts', type_='foreignkey')
    op.drop_constraint('ibyakoreshejwe_ibfk_3', 'ibyakoreshejwe', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('ibyakoreshejwe_ibfk_3', 'ibyakoreshejwe', 'umusaruro', ['umusaruro_resi'], ['id'])
    op.create_foreign_key('coopMemberBankAccounts_ibfk_3', 'coopMemberBankAccounts', 'umusaruro', ['umusaruro_resi'], ['id'])
    op.drop_table('inyongeramusaruro')
    # ### end Alembic commands ###
