"""empty message

Revision ID: 542ee92e7310
Revises: 0632cad24de7
Create Date: 2018-10-18 09:06:24.868978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '542ee92e7310'
down_revision = '0632cad24de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusaruro', sa.Column('amafarangaYose', sa.Integer(), nullable=True))
    op.drop_column('umusaruro', 'amafaraYose')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umusaruro', sa.Column('amafaraYose', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('umusaruro', 'amafarangaYose')
    # ### end Alembic commands ###
