"""empty message

Revision ID: 58381a3e529b
Revises: e39250a1dc11
Create Date: 2018-10-18 10:33:07.399369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58381a3e529b'
down_revision = 'e39250a1dc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inyongeramusaruro', sa.Column('amazina', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inyongeramusaruro', 'amazina')
    # ### end Alembic commands ###
