"""empty message

Revision ID: 875138efbb7a
Revises: 58381a3e529b
Create Date: 2018-10-18 11:15:36.752559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875138efbb7a'
down_revision = '58381a3e529b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inyongeramusaruro_ibfk_3', 'inyongeramusaruro', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('inyongeramusaruro_ibfk_3', 'inyongeramusaruro', 'umusaruro', ['umusaruro_resi'], ['id'])
    # ### end Alembic commands ###
