"""empty message

Revision ID: e39250a1dc11
Revises: 542ee92e7310
Create Date: 2018-10-18 10:32:13.065124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39250a1dc11'
down_revision = '542ee92e7310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inyongeramusaruro', sa.Column('umwakaWisarura', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inyongeramusaruro', 'umwakaWisarura')
    # ### end Alembic commands ###
